name: Build and Deploy to GitHub Pages and Vercel

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: production-build
          path: ./dist

  deploy-gh-pages:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-build
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

  deploy-vercel:
    name: Deploy to Vercel
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-build
          path: ./dist

      - name: Deploy to Vercel
        run: |
          vercel deploy ./dist --prod --yes --token ${{ secrets.VERCEL_TOKEN }} \
            --project ${{ secrets.VERCEL_PROJECT_ID }} \
            --confirm
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
